
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'AEEF4FA0D1C0CB1C21171CF83E7816EE'
    
_lr_action_items = {'AND':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,9,9,-3,-2,-4,-8,-10,-7,-6,-9,-11,9,]),'L_PAREN':([0,1,5,9,10,11,12,13,14,15,16,],[1,1,1,1,1,1,1,1,1,1,1,]),'GT':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,10,10,10,-2,10,None,None,10,10,None,None,10,]),'LITERALS':([0,1,5,9,10,11,12,13,14,15,16,],[2,2,2,2,2,2,2,2,2,2,2,]),'GTE':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,11,11,11,-2,11,None,None,11,11,None,None,11,]),'NOT_EQUALS':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,12,12,12,-2,12,-8,-10,None,None,-9,-11,12,]),'FIELDS':([0,1,5,9,10,11,12,13,14,15,16,],[3,3,3,3,3,3,3,3,3,3,3,]),'EQUALS':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,13,13,13,-2,13,-8,-10,None,None,-9,-11,13,]),'R_PAREN':([2,3,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,17,-3,-2,-4,-8,-10,-7,-6,-9,-11,-5,]),'LT':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,14,14,14,-2,14,None,None,14,14,None,None,14,]),'LTE':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,15,15,15,-2,15,None,None,15,15,None,None,15,]),'NOT':([0,1,5,9,10,11,12,13,14,15,16,],[5,5,5,5,5,5,5,5,5,5,5,]),'OR':([2,3,6,7,8,17,18,19,20,21,22,23,24,25,],[-13,-12,16,16,-3,-2,-4,-8,-10,-7,-6,-9,-11,-5,]),'$end':([2,3,4,6,8,17,18,19,20,21,22,23,24,25,],[-13,-12,0,-1,-3,-2,-4,-8,-10,-7,-6,-9,-11,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[4,]),'Z':([0,1,5,9,10,11,12,13,14,15,16,],[6,7,8,18,19,20,21,22,23,24,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Z','S',1,'p_start_prod','parser.py',60),
  ('Z -> L_PAREN Z R_PAREN','Z',3,'p_common_prod_paren','parser.py',66),
  ('Z -> NOT Z','Z',2,'p_common_prod_logical_0','parser.py',73),
  ('Z -> Z AND Z','Z',3,'p_common_prod_logical_1','parser.py',81),
  ('Z -> Z OR Z','Z',3,'p_common_prod_logical_1','parser.py',82),
  ('Z -> Z EQUALS Z','Z',3,'p_common_prod_comparision','parser.py',96),
  ('Z -> Z NOT_EQUALS Z','Z',3,'p_common_prod_comparision','parser.py',97),
  ('Z -> Z GT Z','Z',3,'p_common_prod_comparision','parser.py',98),
  ('Z -> Z LT Z','Z',3,'p_common_prod_comparision','parser.py',99),
  ('Z -> Z GTE Z','Z',3,'p_common_prod_comparision','parser.py',100),
  ('Z -> Z LTE Z','Z',3,'p_common_prod_comparision','parser.py',101),
  ('Z -> FIELDS','Z',1,'p_common_prod_terminal','parser.py',125),
  ('Z -> LITERALS','Z',1,'p_common_prod_terminal','parser.py',126),
]
